### ISSUE TITLE
Pact tests fail with timeout on pact server setup

### ISSUE THREAD

**Issue by anjali-traceIW** [pact-foundation/jest-pact#186]
Getting failing pact tests with error:
```
Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
```
Jest seems to start running tests before the pact server is up. Increasing the timeout range at `index.js:19` seems to resolve this issue:
```
beforeAll(function () { return pactMock.setup(); }, 30000);
```
Using `0.4.5`

**Comment by TimothyJones** [comment]
Are you providing a different timeout with the options? 

With default options, the Jest timeout should already be 30000 by the time that `beforeAll` is called.

**Comment by TimothyJones** [comment]
Oh, apologies - the improved timeout handling was introduced in 0.4.6. Updating will fix your issue :+1:
