### ISSUE TITLE
Support newer jest versions

### ISSUE THREAD

**Issue by pascalbe-dev** [pact-foundation/jest-pact#196]
Currently, installing jest-pact with a newer jest version, like 25.2 ... displays peer dependency warnings. 
Is there a reason, why newer versions of jest are not supported?
I have not seen any issues when running jest-pact with jest 25.2.3.

**Comment by TimothyJones** [comment]
Thanks for the report! I've significantly widened the peer dependency requirement in v0.8.0, which is being released today.
