### ISSUE TITLE
Pact V3 support

### ISSUE THREAD

**Issue by brendan-donegan** [pact-foundation/jest-pact#199]
Hi,

We are using jest-pact in our project and would like to leverage some of the new features in Pact v3. I was wondering if/when v3 support could be added in jest-pact?

**Comment by TimothyJones** [comment]
Thanks for raising this! This has been asked before (although not tracked here) on https://github.com/pact-foundation/pact-js/issues/483 .

At the time, my thinking was we'd add it when the V3 branch is ready for production use, but I feel like more and more people are using V3 now. 

I think it might be better to support it, and instead chase down the remaining issues that prevent V3 being recommended for production.

**Comment by TimothyJones** [comment]
Update: I've published a draft of a V3 compatible jest-pact. You can pick it up at:
```
npm install --save-dev jest-pact@0.9.0-beta.v3
```
Unfortunately, the interface had to change a bit. You can see a usage example in the readme at:

https://github.com/pact-foundation/jest-pact/tree/pact-js-v3#pact-js-v3

I'm not certain about the interface yet, feedback very welcome.

**Comment by TimothyJones** [comment]
@brendan-donegan Did you try out the V3 `pactWith`? How did it go for you?

**Comment by TimothyJones** [comment]
Ah, yes, good point. I’d like to include both, but it’s a bit tricky before the beta pact-js branch is merged, because of the peer dependency.

We’re working on the V3 merge as the highest priority right now.

**Comment by schowave** [comment]
Are there any Updates on the V3 merge?

**Comment by TimothyJones** [comment]
We have the provider since nearly done, but there's still work to do on the consumer side. You can follow along with the project here  https://github.com/pact-foundation/pact-js/projects/3, or join us on slack if you would like to help out

**Comment by YOU54F** [comment]
Great stuff here @TimothyJones & @mefellows 

How have people been finding the new interface?

**Comment by mefellows** [comment]
There are still some minor teething issues/bugs to sort out in the main Pact JS project, and we currently don't have message support (see https://github.com/pact-foundation/pact-js/projects/3).

The JS core now has all of the requisite APIs for Pact JS, so it's just a public API implementation now mainly to go.

**Comment by YOU54F** [comment]
mainlined into master for jest-pact `0.10.1`+ supporting pact-js `10.0.2`+

**Comment by TimothyJones** [comment]
It is probably a good idea to release a 1.0 of jest pact soon
