### ISSUE TITLE
jest-pact depends on Jasmine

### ISSUE THREAD

**Issue by brendan-donegan** [pact-foundation/jest-pact#201]
I'm attempting to upgrade our repo to use jest-circus, but when I do so I get the following error in our packages containing Pact tests:

    ReferenceError: jasmine is not defined

      at ../../../node_modules/jest-pact/index.js:40:17

Presumably jest-pact has some kind of dependency on jasmine - I'm wondering if it's critical or can it be removed?

**Comment by TimothyJones** [comment]
Which version of `jest-pact` are you using? I believe this is [fixed since 0.8.1](https://github.com/pact-foundation/jest-pact/blob/master/CHANGELOG.md) was released.

**Comment by brendan-donegan** [comment]
@TimothyJones that's correct - I realised this after diving into the code on master :)

**Comment by TimothyJones** [comment]
Haha! No worries. Glad it's fixed 👍
