### ISSUE TITLE
Readme example - incorrect method name

### ISSUE THREAD

**Issue by jbrangwyn** [pact-foundation/jest-pact#202]
Hi, 

Thanks for putting this together, it's been really useful.

I think this part of the readme example:
`    it('returns server health', () => // implicit return again
      client.health().then(health => {
        expect(health).toEqual('up');
      }));`

Should in fact be:
`    it('returns server health', () => // implicit return again
      client.getHealth().then(health => {
        expect(health).toEqual('up');
      }));`

**Comment by TimothyJones** [comment]
You’re so right! Good catch. And thanks for the kind words :)

**Comment by TimothyJones** [comment]
Fixed!
