### ISSUE TITLE
Jest 27 support

### ISSUE THREAD

**Issue by Lakitna** [pact-foundation/jest-pact#203]
Because of the peer dependencies, `jest-pact` can't be used with `jest@27`.

In my project, this leads to a dependency conflict with `@angular-builders/jest@12`.

It would be great if `jest-pact` supports `jest@27` :)

**Comment by TimothyJones** [comment]
I can take a look at this next week- in the meantime, happy to take a PR if you’re able to check the breaking changes and see if there’s anything that affects jest-pact (there usually isn’t)

**Comment by TimothyJones** [comment]
Thanks for the report. I'm now releasing 0.9.1 which has jest 27 in the peer deps :+1:
