### ISSUE TITLE
"jest-pact": "0.9.0-beta.v3" not compatible "@pact-foundation/pact": "10.0.0-beta.45",

### ISSUE THREAD

**Issue by schowave** [pact-foundation/jest-pact#204]
When I want to update the pact dependencies in my project from 10.0.0-beta.44 to 10.0.0-beta.45, I get an error while npm install. 

I am currently using "jest-pact": "0.9.0-beta.v3",

Can someone else verify that issue?

**Comment by TimothyJones** [comment]
What error do you get?

**Comment by schowave** [comment]
It is the same error as reported here:
https://github.com/nodejs/node-gyp/issues/2399
and it should be fixed with the PR from here: https://github.com/nodejs/gyp-next/pull/121
I get the error only under windows. 

It as acutally not a problem of jest-pact but of pact-js itself.

**Comment by schowave** [comment]
I managed to get it working by deleting my local pnpm store...
