### ISSUE TITLE
Error occurred in mock service: JSON::ParserError - 757: unexpected token at '"[{}]"'

### ISSUE THREAD

**Issue by krishnaraghavendra** [pact-foundation/jest-pact#205]
I am using jest pact version - 0.9.1, when trying to make a post request , i get the following error  

```
Error occurred in mock service: JSON::ParserError - 757: unexpected token at '"[]"'
node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/json-2.5.1/lib/json/common.rb:216:in `parse'
```

I am making post request using open api generated sdk.

**Comment by TimothyJones** [comment]
Could you tell us more please? What request are you making? How are you setting up the expectation? What other logs are output, and when are you getting this error?

**Comment by TimothyJones** [comment]
Also, is this the same error as #pact-js/783 ?

**Comment by TimothyJones** [comment]
I’m going to close this in favour of https://github.com/pact-foundation/pact-js/issues/783
