### ISSUE TITLE
pact-js 10.0.0 not compatible with jest-pact 0.9.0-beta.v3

### ISSUE THREAD

**Issue by schowave** [pact-foundation/jest-pact#212]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Windows 10
- **Pact Node version**: 10.0.0-beta.62
- **Node Version**: 16.15.0
- **Other Versions**: jest-pact 0.9.0-beta.v3

### Issue Checklist

Please confirm the following:

- [X] I have upgraded to the latest
- [X] I have the read the FAQs in the Readme
- [X] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Compiling the source code and importing 

__import { pactWith } from "jest-pact/v3";__
works.

### Actual behaviour

The test is not compiling, because in the jest-pact/v3/index.js there is an import 

**var pactV3 = require("@pact-foundation/pact/v3");** which should be (with beta.62)

**var pactV3 = require("@pact-foundation/pact");**

and then compilation works again.

### Relevant log files

`   Cannot find module '@pact-foundation/pact/v3' from '../../node_modules/.pnpm/jest-pact@0.9.0-beta.v3_bd5bdb562262fe533fb9de65840e42f8/node_modules/jest-pact/v3/index.js'

    Require stack:
      C:/repos/xxx/xxx/frontend/node_modules/.pnpm/jest-pact@0.9.0-beta.v3_bd5bdb562262fe533fb9de65840e42f8/node_modules/jest-pact/v3/index.js
      src/__tests__/api/pact/XXX.pacttest.ts

      at Resolver.resolveModule (../../node_modules/.pnpm/jest-resolve@27.5.1/node_modules/jest-resolve/build/resolver.js:324:11)`

**Comment by YOU54F** [comment]
Hi thanks for the report @schowave, I have just come across this looks like it occurred in `10.0.0-beta.61+`, will get an update out probably tomorrow now as it's quite late, and look to mainline the jest-pact beta branch now that pact-js v3 is GA

**Comment by YOU54F** [comment]
released in `0.10.1` of pact-js supporting pact-js `10.0.2`+
